name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Rust toolchain
        run: rustup update stable

      - name: Run tests
        run: cargo test --locked
